from django.conf.urls import *
from django.views.generic import TemplateView

urlpatterns = patterns('',
    (r'^/signing-day-2011$', 'myproject.huskers.views.Signing'),
    (r'^/signing-day-2012$', 'myproject.huskers.views.Signing2012'),
    (r'^/signing-day-2013$', 'myproject.huskers.views.Signing2013'),
    (r'^/signing-day-2014$', 'myproject.huskers.views.Signing2014'),
    (r'^/signing-day-2015$', 'myproject.huskers.views.Signing2015'),
    (r'^/signing-day-2016$', 'myproject.huskers.views.Signing2016'),
    (r'^/preview$', 'myproject.huskers.views.Splash'),
    (r'^/recruiting/widget', 'myproject.huskers.views.RecruitingWidget'),
    (r'^/recruiting', 'myproject.huskers.views.Recruiting'),
    (r'^/recruiter/(?P<nameslug>[0-9a-zA-Z_.-]+)$', 'myproject.huskers.views.RecruiterSingle'),
    (r'^/recruiter', 'myproject.huskers.views.Recruiters'),
    (r'^/badges$', 'myproject.huskers.views.BadgesAll'),
    (r'^/badges/(?P<nameslug>[0-9a-zA-Z_.-]+)$', 'myproject.huskers.views.BadgesSingle'),
    (r'^/draft/(?P<year>[0-9]+)$', 'myproject.huskers.views.DraftSingleYear'),
    (r'^/draft/(?P<slug>[a-zA-Z_.-]+)$', 'myproject.huskers.views.DraftSingleTeam'),
    (r'^/draft$', 'myproject.huskers.views.DraftPicks'),
    (r'^/visits/(?P<year>[0-9]+)/(?P<month>[0-9]+)/(?P<day>[0-9]+)$', 'myproject.huskers.views.Visits'),
    (r'^/player/(?P<playername>[a-zA-Z0-9_.-]+)$', 'myproject.huskers.views.PlayerPage'),
    (r'^/class/(?P<year>[0-9]+)/bigboard$', 'myproject.huskers.views.BigBoard'),
    (r'^/class/(?P<year>[0-9]+)/sam$', 'myproject.huskers.views.TargetsSam'),
    (r'^/class/(?P<year>[0-9]+)/targets$', 'myproject.huskers.views.Targets'),
    (r'^/class/(?P<year>[0-9]+)/widget$', 'myproject.huskers.views.YearWidget'),
    (r'^/class/(?P<year>[0-9_.-]+)', 'myproject.huskers.views.Year'),
    (r'^/class$', 'myproject.huskers.views.AllYears'),
    (r'^/state/map/widget$', 'myproject.huskers.views.RecruitingMapWidget'),
    (r'^/state/map$', 'myproject.huskers.views.StateMap'),
    (r'^/state/(?P<state>[a-zA-Z_.-]+)$', 'myproject.huskers.views.State2'),
    (r'^/state$', 'myproject.huskers.views.AllStates'),
    (r'^/search$', 'myproject.huskers.views.Search2'),
    (r'^/main/(?P<year>[0-9_.-]+)$', 'myproject.huskers.views.YearXML'),
    (r'^/main$', 'myproject.huskers.views.StateXML'),
    (r'^', 'myproject.huskers.views.Recruiting'),
)
